export interface Breed {
  id: string
  name: string
  size: 'toy' | 'small' | 'medium' | 'large' | 'giant'
  avgWeightKgMin: number
  avgWeightKgMax: number
}

export const BREEDS: Breed[] = [
  // TOY BREEDS (20)
  { id: 'chihuahua', name: 'Chihuahua', size: 'toy', avgWeightKgMin: 1.5, avgWeightKgMax: 3 },
  { id: 'pomeranian', name: 'Pomeranian', size: 'toy', avgWeightKgMin: 1.9, avgWeightKgMax: 3.5 },
  { id: 'yorkshire-terrier', name: 'Yorkshire Terrier', size: 'toy', avgWeightKgMin: 2, avgWeightKgMax: 3.2 },
  { id: 'maltese', name: 'Maltese', size: 'toy', avgWeightKgMin: 1.8, avgWeightKgMax: 3.6 },
  { id: 'toy-poodle', name: 'Toy Poodle', size: 'toy', avgWeightKgMin: 2, avgWeightKgMax: 4.5 },
  { id: 'papillon', name: 'Papillon', size: 'toy', avgWeightKgMin: 3.6, avgWeightKgMax: 4.5 },
  { id: 'italian-greyhound', name: 'Italian Greyhound', size: 'toy', avgWeightKgMin: 3.6, avgWeightKgMax: 5 },
  { id: 'chinese-crested', name: 'Chinese Crested', size: 'toy', avgWeightKgMin: 2.3, avgWeightKgMax: 5.4 },
  { id: 'toy-fox-terrier', name: 'Toy Fox Terrier', size: 'toy', avgWeightKgMin: 1.5, avgWeightKgMax: 3.5 },
  { id: 'affenpinscher', name: 'Affenpinscher', size: 'toy', avgWeightKgMin: 2.9, avgWeightKgMax: 4.5 },
  { id: 'brussels-griffon', name: 'Brussels Griffon', size: 'toy', avgWeightKgMin: 2.3, avgWeightKgMax: 4.5 },
  { id: 'english-toy-spaniel', name: 'English Toy Spaniel', size: 'toy', avgWeightKgMin: 3.6, avgWeightKgMax: 6.3 },
  { id: 'japanese-chin', name: 'Japanese Chin', size: 'toy', avgWeightKgMin: 1.4, avgWeightKgMax: 4 },
  { id: 'miniature-pinscher', name: 'Miniature Pinscher', size: 'toy', avgWeightKgMin: 3.6, avgWeightKgMax: 4.5 },
  { id: 'silky-terrier', name: 'Silky Terrier', size: 'toy', avgWeightKgMin: 3.6, avgWeightKgMax: 4.5 },
  { id: 'russian-toy', name: 'Russian Toy', size: 'toy', avgWeightKgMin: 1, avgWeightKgMax: 3 },
  { id: 'mi-ki', name: 'Mi-Ki', size: 'toy', avgWeightKgMin: 1.8, avgWeightKgMax: 3.6 },
  { id: 'prague-ratter', name: 'Prague Ratter', size: 'toy', avgWeightKgMin: 1.5, avgWeightKgMax: 3.5 },
  { id: 'toy-manchester-terrier', name: 'Toy Manchester Terrier', size: 'toy', avgWeightKgMin: 2.7, avgWeightKgMax: 5.4 },
  { id: 'bolognese', name: 'Bolognese', size: 'toy', avgWeightKgMin: 2.5, avgWeightKgMax: 4 },

  // SMALL BREEDS (50)
  { id: 'shih-tzu', name: 'Shih Tzu', size: 'small', avgWeightKgMin: 4, avgWeightKgMax: 7.2 },
  { id: 'pug', name: 'Pug', size: 'small', avgWeightKgMin: 6, avgWeightKgMax: 8 },
  { id: 'beagle', name: 'Beagle', size: 'small', avgWeightKgMin: 9, avgWeightKgMax: 11 },
  { id: 'french-bulldog', name: 'French Bulldog', size: 'small', avgWeightKgMin: 8, avgWeightKgMax: 13 },
  { id: 'cavalier-king-charles', name: 'Cavalier King Charles Spaniel', size: 'small', avgWeightKgMin: 5.9, avgWeightKgMax: 8.2 },
  { id: 'miniature-schnauzer', name: 'Miniature Schnauzer', size: 'small', avgWeightKgMin: 5.4, avgWeightKgMax: 9 },
  { id: 'dachshund', name: 'Dachshund', size: 'small', avgWeightKgMin: 7, avgWeightKgMax: 14 },
  { id: 'cocker-spaniel', name: 'Cocker Spaniel', size: 'small', avgWeightKgMin: 9, avgWeightKgMax: 13.6 },
  { id: 'west-highland-terrier', name: 'West Highland White Terrier', size: 'small', avgWeightKgMin: 6.8, avgWeightKgMax: 9 },
  { id: 'bichon-frise', name: 'Bichon Frise', size: 'small', avgWeightKgMin: 5, avgWeightKgMax: 8 },
  { id: 'boston-terrier', name: 'Boston Terrier', size: 'small', avgWeightKgMin: 4.5, avgWeightKgMax: 11 },
  { id: 'havanese', name: 'Havanese', size: 'small', avgWeightKgMin: 3.2, avgWeightKgMax: 5.9 },
  { id: 'pembroke-welsh-corgi', name: 'Pembroke Welsh Corgi', size: 'small', avgWeightKgMin: 11, avgWeightKgMax: 14 },
  { id: 'miniature-poodle', name: 'Miniature Poodle', size: 'small', avgWeightKgMin: 4.5, avgWeightKgMax: 7 },
  { id: 'scottish-terrier', name: 'Scottish Terrier', size: 'small', avgWeightKgMin: 8.5, avgWeightKgMax: 10.5 },
  { id: 'cairn-terrier', name: 'Cairn Terrier', size: 'small', avgWeightKgMin: 5.9, avgWeightKgMax: 7.5 },
  { id: 'lhasa-apso', name: 'Lhasa Apso', size: 'small', avgWeightKgMin: 5.4, avgWeightKgMax: 8 },
  { id: 'pekingese', name: 'Pekingese', size: 'small', avgWeightKgMin: 3.2, avgWeightKgMax: 6.4 },
  { id: 'welsh-corgi-cardigan', name: 'Cardigan Welsh Corgi', size: 'small', avgWeightKgMin: 11, avgWeightKgMax: 17 },
  { id: 'norfolk-terrier', name: 'Norfolk Terrier', size: 'small', avgWeightKgMin: 4.5, avgWeightKgMax: 6 },
  { id: 'norwich-terrier', name: 'Norwich Terrier', size: 'small', avgWeightKgMin: 4.5, avgWeightKgMax: 6 },
  { id: 'rat-terrier', name: 'Rat Terrier', size: 'small', avgWeightKgMin: 4.5, avgWeightKgMax: 11 },
  { id: 'schipperke', name: 'Schipperke', size: 'small', avgWeightKgMin: 3.6, avgWeightKgMax: 7 },
  { id: 'basenji', name: 'Basenji', size: 'small', avgWeightKgMin: 9, avgWeightKgMax: 12 },
  { id: 'shiba-inu', name: 'Shiba Inu', size: 'small', avgWeightKgMin: 8, avgWeightKgMax: 11 },
  { id: 'coton-de-tulear', name: 'Coton de Tulear', size: 'small', avgWeightKgMin: 3.5, avgWeightKgMax: 6 },
  { id: 'jack-russell', name: 'Jack Russell Terrier', size: 'small', avgWeightKgMin: 5.9, avgWeightKgMax: 8 },
  { id: 'parson-russell', name: 'Parson Russell Terrier', size: 'small', avgWeightKgMin: 5.9, avgWeightKgMax: 8 },
  { id: 'american-eskimo-toy', name: 'American Eskimo (Toy)', size: 'small', avgWeightKgMin: 2.7, avgWeightKgMax: 4.5 },
  { id: 'maltipoo', name: 'Maltipoo', size: 'small', avgWeightKgMin: 2.3, avgWeightKgMax: 5.4 },
  { id: 'pomchi', name: 'Pomchi', size: 'small', avgWeightKgMin: 2.3, avgWeightKgMax: 4.5 },
  { id: 'teddy-bear', name: 'Teddy Bear (Zuchon)', size: 'small', avgWeightKgMin: 3.6, avgWeightKgMax: 5.4 },
  { id: 'miniature-dachshund', name: 'Miniature Dachshund', size: 'small', avgWeightKgMin: 3.5, avgWeightKgMax: 5 },
  { id: 'miniature-bull-terrier', name: 'Miniature Bull Terrier', size: 'small', avgWeightKgMin: 11, avgWeightKgMax: 15 },
  { id: 'glen-of-imaal', name: 'Glen of Imaal Terrier', size: 'small', avgWeightKgMin: 14, avgWeightKgMax: 16 },
  { id: 'sealyham-terrier', name: 'Sealyham Terrier', size: 'small', avgWeightKgMin: 8, avgWeightKgMax: 9 },
  { id: 'skye-terrier', name: 'Skye Terrier', size: 'small', avgWeightKgMin: 8, avgWeightKgMax: 11 },
  { id: 'dandie-dinmont', name: 'Dandie Dinmont Terrier', size: 'small', avgWeightKgMin: 8, avgWeightKgMax: 11 },
  { id: 'border-terrier', name: 'Border Terrier', size: 'small', avgWeightKgMin: 5, avgWeightKgMax: 7 },
  { id: 'lakeland-terrier', name: 'Lakeland Terrier', size: 'small', avgWeightKgMin: 6.8, avgWeightKgMax: 7.7 },
  { id: 'wire-fox-terrier', name: 'Wire Fox Terrier', size: 'small', avgWeightKgMin: 7.3, avgWeightKgMax: 8.6 },
  { id: 'smooth-fox-terrier', name: 'Smooth Fox Terrier', size: 'small', avgWeightKgMin: 7.3, avgWeightKgMax: 8.6 },
  { id: 'welsh-terrier', name: 'Welsh Terrier', size: 'small', avgWeightKgMin: 9, avgWeightKgMax: 10 },
  { id: 'tibetan-spaniel', name: 'Tibetan Spaniel', size: 'small', avgWeightKgMin: 4, avgWeightKgMax: 7 },
  { id: 'tibetan-terrier', name: 'Tibetan Terrier', size: 'small', avgWeightKgMin: 8, avgWeightKgMax: 14 },
  { id: 'lowchen', name: 'Lowchen', size: 'small', avgWeightKgMin: 4, avgWeightKgMax: 8 },
  { id: 'american-eskimo-miniature', name: 'American Eskimo (Miniature)', size: 'small', avgWeightKgMin: 4.5, avgWeightKgMax: 9 },
  { id: 'portuguese-podengo', name: 'Portuguese Podengo (Small)', size: 'small', avgWeightKgMin: 4, avgWeightKgMax: 6 },
  { id: 'xoloitzcuintli-miniature', name: 'Xoloitzcuintli (Miniature)', size: 'small', avgWeightKgMin: 4.5, avgWeightKgMax: 14 },
  { id: 'miniature-american-shepherd', name: 'Miniature American Shepherd', size: 'small', avgWeightKgMin: 9, avgWeightKgMax: 18 },

  // MEDIUM BREEDS (71)
  { id: 'labrador-retriever', name: 'Labrador Retriever', size: 'medium', avgWeightKgMin: 25, avgWeightKgMax: 36 },
  { id: 'golden-retriever', name: 'Golden Retriever', size: 'medium', avgWeightKgMin: 25, avgWeightKgMax: 34 },
  { id: 'border-collie', name: 'Border Collie', size: 'medium', avgWeightKgMin: 14, avgWeightKgMax: 20 },
  { id: 'australian-shepherd', name: 'Australian Shepherd', size: 'medium', avgWeightKgMin: 16, avgWeightKgMax: 32 },
  { id: 'bulldog', name: 'Bulldog', size: 'medium', avgWeightKgMin: 18, avgWeightKgMax: 25 },
  { id: 'standard-poodle', name: 'Standard Poodle', size: 'medium', avgWeightKgMin: 20, avgWeightKgMax: 32 },
  { id: 'siberian-husky', name: 'Siberian Husky', size: 'medium', avgWeightKgMin: 16, avgWeightKgMax: 27 },
  { id: 'boxer', name: 'Boxer', size: 'medium', avgWeightKgMin: 25, avgWeightKgMax: 32 },
  { id: 'springer-spaniel', name: 'English Springer Spaniel', size: 'medium', avgWeightKgMin: 18, avgWeightKgMax: 25 },
  { id: 'brittany', name: 'Brittany', size: 'medium', avgWeightKgMin: 14, avgWeightKgMax: 18 },
  { id: 'whippet', name: 'Whippet', size: 'medium', avgWeightKgMin: 12, avgWeightKgMax: 18 },
  { id: 'vizsla', name: 'Vizsla', size: 'medium', avgWeightKgMin: 20, avgWeightKgMax: 29 },
  { id: 'weimaraner', name: 'Weimaraner', size: 'medium', avgWeightKgMin: 25, avgWeightKgMax: 40 },
  { id: 'dalmatian', name: 'Dalmatian', size: 'medium', avgWeightKgMin: 20, avgWeightKgMax: 32 },
  { id: 'portuguese-water-dog', name: 'Portuguese Water Dog', size: 'medium', avgWeightKgMin: 16, avgWeightKgMax: 25 },
  { id: 'samoyed', name: 'Samoyed', size: 'medium', avgWeightKgMin: 16, avgWeightKgMax: 30 },
  { id: 'chow-chow', name: 'Chow Chow', size: 'medium', avgWeightKgMin: 20, avgWeightKgMax: 32 },
  { id: 'shar-pei', name: 'Shar Pei', size: 'medium', avgWeightKgMin: 18, avgWeightKgMax: 29 },
  { id: 'american-staffordshire', name: 'American Staffordshire Terrier', size: 'medium', avgWeightKgMin: 18, avgWeightKgMax: 32 },
  { id: 'bull-terrier', name: 'Bull Terrier', size: 'medium', avgWeightKgMin: 18, avgWeightKgMax: 32 },
  { id: 'airedale-terrier', name: 'Airedale Terrier', size: 'medium', avgWeightKgMin: 18, avgWeightKgMax: 29 },
  { id: 'standard-schnauzer', name: 'Standard Schnauzer', size: 'medium', avgWeightKgMin: 14, avgWeightKgMax: 20 },
  { id: 'keeshond', name: 'Keeshond', size: 'medium', avgWeightKgMin: 14, avgWeightKgMax: 18 },
  { id: 'american-cocker-spaniel', name: 'American Cocker Spaniel', size: 'medium', avgWeightKgMin: 10, avgWeightKgMax: 13 },
  { id: 'nova-scotia-duck-tolling', name: 'Nova Scotia Duck Tolling Retriever', size: 'medium', avgWeightKgMin: 17, avgWeightKgMax: 23 },
  { id: 'soft-coated-wheaten', name: 'Soft Coated Wheaten Terrier', size: 'medium', avgWeightKgMin: 14, avgWeightKgMax: 20 },
  { id: 'norwegian-elkhound', name: 'Norwegian Elkhound', size: 'medium', avgWeightKgMin: 20, avgWeightKgMax: 25 },
  { id: 'irish-water-spaniel', name: 'Irish Water Spaniel', size: 'medium', avgWeightKgMin: 20, avgWeightKgMax: 30 },
  { id: 'flat-coated-retriever', name: 'Flat-Coated Retriever', size: 'medium', avgWeightKgMin: 25, avgWeightKgMax: 36 },
  { id: 'curly-coated-retriever', name: 'Curly-Coated Retriever', size: 'medium', avgWeightKgMin: 23, avgWeightKgMax: 41 },
  { id: 'field-spaniel', name: 'Field Spaniel', size: 'medium', avgWeightKgMin: 16, avgWeightKgMax: 25 },
  { id: 'welsh-springer-spaniel', name: 'Welsh Springer Spaniel', size: 'medium', avgWeightKgMin: 16, avgWeightKgMax: 20 },
  { id: 'german-wirehaired', name: 'German Wirehaired Pointer', size: 'medium', avgWeightKgMin: 20, avgWeightKgMax: 32 },
  { id: 'german-shorthaired', name: 'German Shorthaired Pointer', size: 'medium', avgWeightKgMin: 20, avgWeightKgMax: 32 },
  { id: 'spinone-italiano', name: 'Spinone Italiano', size: 'medium', avgWeightKgMin: 29, avgWeightKgMax: 39 },
  { id: 'lagotto-romagnolo', name: 'Lagotto Romagnolo', size: 'medium', avgWeightKgMin: 13, avgWeightKgMax: 16 },
  { id: 'boykin-spaniel', name: 'Boykin Spaniel', size: 'medium', avgWeightKgMin: 11, avgWeightKgMax: 18 },
  { id: 'icelandic-sheepdog', name: 'Icelandic Sheepdog', size: 'medium', avgWeightKgMin: 9, avgWeightKgMax: 14 },
  { id: 'finnish-spitz', name: 'Finnish Spitz', size: 'medium', avgWeightKgMin: 7, avgWeightKgMax: 13 },
  { id: 'canaan-dog', name: 'Canaan Dog', size: 'medium', avgWeightKgMin: 16, avgWeightKgMax: 25 },
  { id: 'australian-cattle-dog', name: 'Australian Cattle Dog', size: 'medium', avgWeightKgMin: 14, avgWeightKgMax: 16 },
  { id: 'belgian-tervuren', name: 'Belgian Tervuren', size: 'medium', avgWeightKgMin: 20, avgWeightKgMax: 30 },
  { id: 'belgian-sheepdog', name: 'Belgian Sheepdog', size: 'medium', avgWeightKgMin: 20, avgWeightKgMax: 30 },
  { id: 'belgian-malinois', name: 'Belgian Malinois', size: 'medium', avgWeightKgMin: 20, avgWeightKgMax: 30 },
  { id: 'dutch-shepherd', name: 'Dutch Shepherd', size: 'medium', avgWeightKgMin: 20, avgWeightKgMax: 30 },
  { id: 'croatian-sheepdog', name: 'Croatian Sheepdog', size: 'medium', avgWeightKgMin: 13, avgWeightKgMax: 20 },
  { id: 'bearded-collie', name: 'Bearded Collie', size: 'medium', avgWeightKgMin: 18, avgWeightKgMax: 27 },
  { id: 'rough-collie', name: 'Rough Collie', size: 'medium', avgWeightKgMin: 18, avgWeightKgMax: 34 },
  { id: 'smooth-collie', name: 'Smooth Collie', size: 'medium', avgWeightKgMin: 18, avgWeightKgMax: 34 },
  { id: 'shetland-sheepdog', name: 'Shetland Sheepdog', size: 'medium', avgWeightKgMin: 6, avgWeightKgMax: 12 },
  { id: 'old-english-sheepdog', name: 'Old English Sheepdog', size: 'medium', avgWeightKgMin: 27, avgWeightKgMax: 45 },
  { id: 'bouvier-des-flandres', name: 'Bouvier des Flandres', size: 'medium', avgWeightKgMin: 27, avgWeightKgMax: 40 },
  { id: 'briard', name: 'Briard', size: 'medium', avgWeightKgMin: 23, avgWeightKgMax: 41 },
  { id: 'puli', name: 'Puli', size: 'medium', avgWeightKgMin: 10, avgWeightKgMax: 15 },
  { id: 'pumi', name: 'Pumi', size: 'medium', avgWeightKgMin: 8, avgWeightKgMax: 13 },
  { id: 'mudi', name: 'Mudi', size: 'medium', avgWeightKgMin: 8, avgWeightKgMax: 13 },
  { id: 'polish-lowland-sheepdog', name: 'Polish Lowland Sheepdog', size: 'medium', avgWeightKgMin: 14, avgWeightKgMax: 23 },
  { id: 'american-water-spaniel', name: 'American Water Spaniel', size: 'medium', avgWeightKgMin: 14, avgWeightKgMax: 20 },
  { id: 'english-setter', name: 'English Setter', size: 'medium', avgWeightKgMin: 20, avgWeightKgMax: 36 },
  { id: 'irish-red-white-setter', name: 'Irish Red and White Setter', size: 'medium', avgWeightKgMin: 25, avgWeightKgMax: 32 },
  { id: 'gordon-setter', name: 'Gordon Setter', size: 'medium', avgWeightKgMin: 20, avgWeightKgMax: 29 },
  { id: 'chesapeake-bay-retriever', name: 'Chesapeake Bay Retriever', size: 'medium', avgWeightKgMin: 25, avgWeightKgMax: 36 },
  { id: 'irish-setter', name: 'Irish Setter', size: 'medium', avgWeightKgMin: 27, avgWeightKgMax: 32 },
  { id: 'harrier', name: 'Harrier', size: 'medium', avgWeightKgMin: 18, avgWeightKgMax: 27 },
  { id: 'treeing-walker-coonhound', name: 'Treeing Walker Coonhound', size: 'medium', avgWeightKgMin: 23, avgWeightKgMax: 32 },
  { id: 'plott-hound', name: 'Plott Hound', size: 'medium', avgWeightKgMin: 18, avgWeightKgMax: 27 },
  { id: 'redbone-coonhound', name: 'Redbone Coonhound', size: 'medium', avgWeightKgMin: 23, avgWeightKgMax: 32 },
  { id: 'bluetick-coonhound', name: 'Bluetick Coonhound', size: 'medium', avgWeightKgMin: 20, avgWeightKgMax: 36 },
  { id: 'black-tan-coonhound', name: 'Black and Tan Coonhound', size: 'medium', avgWeightKgMin: 23, avgWeightKgMax: 34 },
  { id: 'ibizan-hound', name: 'Ibizan Hound', size: 'medium', avgWeightKgMin: 20, avgWeightKgMax: 29 },
  { id: 'pharaoh-hound', name: 'Pharaoh Hound', size: 'medium', avgWeightKgMin: 18, avgWeightKgMax: 25 },

  // LARGE BREEDS (38)
  { id: 'german-shepherd', name: 'German Shepherd', size: 'large', avgWeightKgMin: 22, avgWeightKgMax: 40 },
  { id: 'rottweiler', name: 'Rottweiler', size: 'large', avgWeightKgMin: 35, avgWeightKgMax: 60 },
  { id: 'doberman', name: 'Doberman Pinscher', size: 'large', avgWeightKgMin: 27, avgWeightKgMax: 45 },
  { id: 'alaskan-malamute', name: 'Alaskan Malamute', size: 'large', avgWeightKgMin: 34, avgWeightKgMax: 43 },
  { id: 'bernese-mountain-dog', name: 'Bernese Mountain Dog', size: 'large', avgWeightKgMin: 32, avgWeightKgMax: 52 },
  { id: 'bloodhound', name: 'Bloodhound', size: 'large', avgWeightKgMin: 36, avgWeightKgMax: 50 },
  { id: 'akita', name: 'Akita', size: 'large', avgWeightKgMin: 32, avgWeightKgMax: 45 },
  { id: 'cane-corso', name: 'Cane Corso', size: 'large', avgWeightKgMin: 40, avgWeightKgMax: 50 },
  { id: 'rhodesian-ridgeback', name: 'Rhodesian Ridgeback', size: 'large', avgWeightKgMin: 29, avgWeightKgMax: 41 },
  { id: 'greater-swiss-mountain-dog', name: 'Greater Swiss Mountain Dog', size: 'large', avgWeightKgMin: 36, avgWeightKgMax: 61 },
  { id: 'giant-schnauzer', name: 'Giant Schnauzer', size: 'large', avgWeightKgMin: 25, avgWeightKgMax: 48 },
  { id: 'komondor', name: 'Komondor', size: 'large', avgWeightKgMin: 36, avgWeightKgMax: 61 },
  { id: 'kuvasz', name: 'Kuvasz', size: 'large', avgWeightKgMin: 32, avgWeightKgMax: 52 },
  { id: 'black-russian-terrier', name: 'Black Russian Terrier', size: 'large', avgWeightKgMin: 36, avgWeightKgMax: 65 },
  { id: 'dogue-de-bordeaux', name: 'Dogue de Bordeaux', size: 'large', avgWeightKgMin: 54, avgWeightKgMax: 68 },
  { id: 'bullmastiff', name: 'Bullmastiff', size: 'large', avgWeightKgMin: 41, avgWeightKgMax: 59 },
  { id: 'central-asian-shepherd', name: 'Central Asian Shepherd', size: 'large', avgWeightKgMin: 40, avgWeightKgMax: 79 },
  { id: 'caucasian-shepherd', name: 'Caucasian Shepherd', size: 'large', avgWeightKgMin: 45, avgWeightKgMax: 77 },
  { id: 'perro-de-presa-canario', name: 'Perro de Presa Canario', size: 'large', avgWeightKgMin: 38, avgWeightKgMax: 59 },
  { id: 'estrela-mountain-dog', name: 'Estrela Mountain Dog', size: 'large', avgWeightKgMin: 30, avgWeightKgMax: 50 },
  { id: 'hovawart', name: 'Hovawart', size: 'large', avgWeightKgMin: 25, avgWeightKgMax: 40 },
  { id: 'south-russian-ovcharka', name: 'South Russian Ovcharka', size: 'large', avgWeightKgMin: 48, avgWeightKgMax: 50 },
  { id: 'tornjak', name: 'Tornjak', size: 'large', avgWeightKgMin: 28, avgWeightKgMax: 50 },
  { id: 'sarplaninac', name: 'Sarplaninac', size: 'large', avgWeightKgMin: 30, avgWeightKgMax: 45 },
  { id: 'karst-shepherd', name: 'Karst Shepherd', size: 'large', avgWeightKgMin: 25, avgWeightKgMax: 42 },
  { id: 'rafeiro-do-alentejo', name: 'Rafeiro do Alentejo', size: 'large', avgWeightKgMin: 35, avgWeightKgMax: 60 },
  { id: 'castro-laboreiro', name: 'Castro Laboreiro Dog', size: 'large', avgWeightKgMin: 25, avgWeightKgMax: 40 },
  { id: 'portuguese-sheepdog', name: 'Portuguese Sheepdog', size: 'large', avgWeightKgMin: 17, avgWeightKgMax: 27 },
  { id: 'mucuchies', name: 'Mucuchies', size: 'large', avgWeightKgMin: 34, avgWeightKgMax: 50 },
  { id: 'greenland-dog', name: 'Greenland Dog', size: 'large', avgWeightKgMin: 30, avgWeightKgMax: 32 },
  { id: 'canadian-eskimo-dog', name: 'Canadian Eskimo Dog', size: 'large', avgWeightKgMin: 20, avgWeightKgMax: 40 },
  { id: 'chinook', name: 'Chinook', size: 'large', avgWeightKgMin: 25, avgWeightKgMax: 41 },
  { id: 'tamaskan', name: 'Tamaskan', size: 'large', avgWeightKgMin: 23, avgWeightKgMax: 45 },
  { id: 'utonagan', name: 'Utonagan', size: 'large', avgWeightKgMin: 25, avgWeightKgMax: 50 },
  { id: 'northern-inuit', name: 'Northern Inuit Dog', size: 'large', avgWeightKgMin: 25, avgWeightKgMax: 50 },
  { id: 'american-akita', name: 'American Akita', size: 'large', avgWeightKgMin: 32, avgWeightKgMax: 59 },
  { id: 'shikoku', name: 'Shikoku', size: 'large', avgWeightKgMin: 16, avgWeightKgMax: 26 },
  { id: 'kishu-ken', name: 'Kishu Ken', size: 'large', avgWeightKgMin: 13, avgWeightKgMax: 27 },

  // GIANT BREEDS (25)
  { id: 'great-dane', name: 'Great Dane', size: 'giant', avgWeightKgMin: 45, avgWeightKgMax: 90 },
  { id: 'saint-bernard', name: 'Saint Bernard', size: 'giant', avgWeightKgMin: 54, avgWeightKgMax: 82 },
  { id: 'mastiff', name: 'Mastiff', size: 'giant', avgWeightKgMin: 54, avgWeightKgMax: 100 },
  { id: 'newfoundland', name: 'Newfoundland', size: 'giant', avgWeightKgMin: 45, avgWeightKgMax: 68 },
  { id: 'great-pyrenees', name: 'Great Pyrenees', size: 'giant', avgWeightKgMin: 36, avgWeightKgMax: 54 },
  { id: 'tibetan-mastiff', name: 'Tibetan Mastiff', size: 'giant', avgWeightKgMin: 41, avgWeightKgMax: 68 },
  { id: 'irish-wolfhound', name: 'Irish Wolfhound', size: 'giant', avgWeightKgMin: 48, avgWeightKgMax: 70 },
  { id: 'leonberger', name: 'Leonberger', size: 'giant', avgWeightKgMin: 45, avgWeightKgMax: 77 },
  { id: 'landseer', name: 'Landseer', size: 'giant', avgWeightKgMin: 45, avgWeightKgMax: 80 },
  { id: 'neapolitan-mastiff', name: 'Neapolitan Mastiff', size: 'giant', avgWeightKgMin: 50, avgWeightKgMax: 70 },
  { id: 'scottish-deerhound', name: 'Scottish Deerhound', size: 'giant', avgWeightKgMin: 34, avgWeightKgMax: 50 },
  { id: 'spanish-mastiff', name: 'Spanish Mastiff', size: 'giant', avgWeightKgMin: 52, avgWeightKgMax: 100 },
  { id: 'pyrenean-mastiff', name: 'Pyrenean Mastiff', size: 'giant', avgWeightKgMin: 54, avgWeightKgMax: 80 },
  { id: 'tosa-inu', name: 'Tosa Inu', size: 'giant', avgWeightKgMin: 36, avgWeightKgMax: 61 },
  { id: 'anatolian-shepherd', name: 'Anatolian Shepherd', size: 'giant', avgWeightKgMin: 40, avgWeightKgMax: 65 },
  { id: 'boz-shepherd', name: 'Boz Shepherd', size: 'giant', avgWeightKgMin: 50, avgWeightKgMax: 90 },
  { id: 'kangal', name: 'Kangal Shepherd Dog', size: 'giant', avgWeightKgMin: 41, avgWeightKgMax: 66 },
  { id: 'aksaray-malaklisi', name: 'Aksaray Malaklisi', size: 'giant', avgWeightKgMin: 55, avgWeightKgMax: 100 },
  { id: 'boerboel', name: 'Boerboel', size: 'giant', avgWeightKgMin: 54, avgWeightKgMax: 90 },
  { id: 'moscovian-watchdog', name: 'Moscovian Watchdog', size: 'giant', avgWeightKgMin: 45, avgWeightKgMax: 68 },
  { id: 'broholmer', name: 'Broholmer', size: 'giant', avgWeightKgMin: 40, avgWeightKgMax: 70 },
  { id: 'caucasian-ovcharka', name: 'Caucasian Ovcharka', size: 'giant', avgWeightKgMin: 45, avgWeightKgMax: 100 },
  { id: 'central-asian-ovcharka', name: 'Central Asian Ovcharka', size: 'giant', avgWeightKgMin: 40, avgWeightKgMax: 79 },
  { id: 'kurdish-kangal', name: 'Kurdish Kangal', size: 'giant', avgWeightKgMin: 45, avgWeightKgMax: 80 },
  { id: 'caucasian-mountain-dog', name: 'Caucasian Mountain Dog', size: 'giant', avgWeightKgMin: 45, avgWeightKgMax: 90 },
]

export function getBreedsBySize(size: Breed['size']): Breed[] {
  return BREEDS.filter(b => b.size === size)
}

export function getBreedById(id: string): Breed | undefined {
  return BREEDS.find(b => b.id === id)
}

export function getAvgWeight(breed: Breed): number {
  return Math.round((breed.avgWeightKgMin + breed.avgWeightKgMax) / 2)
}
